function [t, x, y, z, u] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [T, X, Y, Z, U] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [T, X, Y, Z, U] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [t, x, y, z, u] = importfile("S:\RunningCode\SaulStudio\ren1000_vertical_numel_negative1000.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Oct-2025 10:25:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "x", "y", "z", "u"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
vertical_numel = readtable(filename, opts);

%% Convert to output type
t = vertical_numel.t;
x = vertical_numel.x;
y = vertical_numel.y;
z = vertical_numel.z;
u = vertical_numel.u;
end