
#ifndef BL_AMREX_H
#define BL_AMREX_H
#include <AMReX_Config.H>

#include <AMReX_GpuQualifiers.H>
#include <AMReX_GpuPrint.H>
#include <AMReX_GpuAssert.H>
#include <AMReX_ccse-mpi.H>
#include <AMReX_Exception.H>
#include <AMReX_Extension.H>

#include <functional>
#include <iostream>
#include <memory>
#include <string>
#include <vector>


/*
 This class consists of user-defined contexts for the program computation
*/

  
    class amress_solver
    {
    public:
      //amress_solver ();
      //  ~amress_solver ();
      //  amress_solver (amress_solver const&) = delete;
      //  amress_solver (amress_solver &&) = delete;
      //  amress_solver& operator= (amress_solver const&) = delete;
      //  amress_solver& operator= (amress_solver &&) = delete;
      int test_value;

        
    
    };


#endif /*BL_AMREX_H*/
